---
swagger: '2.0'
info:
  description: Документация описывает формат сообщений, отправляемых мерчанту на определенные события,
  происходящие в платежной системе (например, изменение статуса инвойса или платежа).
  Вебхук — это подписка на такое событие в системе. Он представляет собой url-адрес, тип события и набор фильтров.
  Когда наступает одно из событий, платежная система выбирает подходящие вебхуки и рассылает сообщения на указанные в них url-адреса.
  Если подходящих подписок несколько, то события отправляются параллельно на все адреса.
  Список возможных типов событий -
  >invoice.created
  >invoice.status.changed
  >payment.created
  >payment.status.changed
  Запрос — HTTP-запрос сервера платежной системы к системе мерчанта с информацией о событии.
  Ответ — HTTP-ответ системы мерчанта на запрос от сервера платежной системы.

  Безопасноть.
  Платежная система подтверждает свою подлинность, подписывая сообщения приватным ключом RSA с алгоритмом хэширования SHA-256.
  Приватный и публичный ключи задаются в настройках вебхука.
  Подпись передается в HTTP-заголовке X-Signature в формате Base64.

  Очередь отправки.
  Если url-адрес вебхука недоступен или отвечает ошибкой 500, то сервер платежной системы
  будет переотправлять событие 4 раза с интервалами 30сек, 5мин, 15мин, 1час.
  Если и в этом случае не удалось отправить событие, то отправка на данный url останавливается.
  Очередность отправки событий при этом сохраняется - это означает, что никакие события не могут быть пропущены. 
  version: '1.0'
  title: Webhook events documentation
  termsOfService: 'http://rbkmoney.com/'
  contact:
    name: RBKmoney support team
    email: support@rbk.money
    url: 'https://api.rbk.money'
schemes:
  - https
consumes:
  - application/json; charset=utf-8
produces:
  - application/json; charset=utf-8
parameters:
  requestID:
    name: X-Request-ID
    in: header
    description: Уникальный идентификатор запроса к системе
    required: true
    type: string
    maxLength: 32
  xsignature:
    name: X-Signature
    in: header
    description: Подпись сообщения, созданная приватным ключом RSA с алгоритмом хэширования SHA-256 и размером ключа 1024.
    required: true
    type: string
tags:
- name: EventProcessing
  description: Обработка сообщения по собтыию платежной системы
paths:
  "/webhook-url":
    post:
      tags:
      - EventProcessing
      summary: Обработка сообщения по событию платежной системы
      operationId: processWebhookEvent
      parameters:
      - $ref: "#/parameters/requestID"
      - $ref: "#/parameters/xsignature"
      - in: body
        name: invoiceInfo
        description: Тело запроса, содержащее необходимую информацию о событии
        required: true
        schema:
          "$ref": "#/definitions/EventInfo"
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/InvoiceInfoResponse"
        '400':
          description: Bad Request
          schema:
            "$ref": "#/definitions/InvoiceInfoResponse"
        '500':
          description: Internal Error
definitions:
  EventInfo:
    description: Тело информации о событии в системе
    type: object
    required:
      - event_id
      - event_time
      - event_type
    properties:
      event_id:
        description: Идентификатор события в системе
        type: string
      event_time:
        description: Дата и время события
        type: string
        format: date-time
      event_type:
        description: Тип события (один из списка возможных типов событий)
        enum:
          - invoice.created
          - invoice.status.changed
          - payment.created
          - payment.status.changed
      payload:
        schema:
          $ref: "#/definitions/InvoiceInfo"
  InvoiceInfo:
    description: Тело с детальной инфомацией об инвойсе или платеже
    type: object
    required:
      - amount
      - created_at
      - currency
      - event_type
      - invoice_id
      - metadata
      - shop_id
      - status
    properties:
      amount:
        description: Стоимость в минорных денежных единицах
        type: integer
        format: int64
      created_at:
        description: Дата и время создания
        type: string
        format: date-time
      currency:
        description: |
          Валюта, символьный код согласно
          [RFC 4217](http://www.iso.org/iso/home/standards/currency_codes.htm).
        type: string
      event_type:
        description: Тип сообщения (инвойс или платеж)
        type: string
        enum:
          - invoice
          - payment
      invoice_id:
        description: Идентификатор инвойса
        type: string
      metadata:
        description: Связанные с инвойсом метаданные
        type: object
      payment_id:
        description: Идентификатор платежа (если значение параметра event_type равно payment)
        type: string
      shop_id:
        description: Идентификатор магазина
        type: integer
        format: int32
      status:
        description: Статус инвойса (или платежа, в зависимости от значения параметра event_type)
        type: string
        enum:
          - unpaid
          - cancelled
          - paid
          - refunded
          - fulfilled
          - pending
          - processed
          - captured
          - failed
  InvoiceInfoResponse:
    type: object
    properties:
      message:
        description: Дополнительная информация
        type: string
