swagger: '2.0'
info:
  version: '1.0'
  title: RBKmoney Webhooks Events API
  termsOfService: 'http://rbkmoney.com/'
  contact:
    name: RBKmoney support team
    email: tech-support@rbkmoney.com
    url: 'https://api.rbk.money'
  description: |

    ## Webhooks Events API

    Данная спецификация определяет протокол доставки оповещений о возникновении
    новых событий в рамках вашей организации, которые платформа доставляет в
    виде HTTP-запросов на URL-адреса созданных вами webhook'ов. Обработчики для
    подобного рода запросов необходимо реализовать на стороне вашего серверного
    кода согласно данной спецификации.

    Webhook — это подписка на определенный тип события либо их группу,
    касающихся различных объектов в рамках вашей организации. Для управления
    webhook'ами используются методы RBKmoney API, описанные в спецификации
    [RBKmoney Webhooks Management API](https://rbkmoney.github.io/api#Webhooks).
    Когда наступает одно из событий в рамках определенного инвойса (например,
    изменение статуса инвойса или платежа по этому инвойсу), платформа выбирает
    webhook, подходящий под этот тип события, и отправляет HTTP-запрос,
    содержащий сообщение в формате JSON на указанный в этом webhook'е URL. Если
    вы создали несколько webhook'ов, подходящих под этот тип события, то событие
    доставляется одновременно на все заданные в них URL в неопределённом
    порядке.

    ## Стратегия доставки оповещений

    Платформа гарантирует порядок доставки событий, никакое событие не может
    быть пропущено и доставлено не в порядке возникновения в платформе.
    Платформа поддерживает очередь сообщений для каждого webhook'а для того,
    чтобы соблюсти эти гарантии.

    Запрос на доставку считается успешным только при получении ответа со
    статусом `200`. Платформа будет ожидать успешного ответа на отправленный
    запрос в течение 10 секунд. В случае ответа любым другим статусом или по
    истечении указанного времени, отведённого на обработку оповещения, платформа
    будет пытаться повторно доставить оповещения до получения успешного ответа,
    либо до принятия решения о невозможности доставить информацию. Попытки
    доставки будут производится со следующими временными интервалами между
    запросами:

      - 30 секунд,
      - 5 минут,
      - 15 минут,
      - 1 час.

    Если последняя попытка доставить оповещение оканчивается неудачей,
    соответствующий webhook помечается как выключенный, и все события, которые
    накопились в очереди этого webhook'а, отбрасываются.

    ## Авторизация полученных оповещений

    Платформа подтверждает подлинность оповещений, подписывая сообщения
    приватным RSA-ключом с алгоритмом хеширования SHA-256, парный публичный ключ
    к которому содержится в данных webhook`а. Подпись передается в HTTP-
    заголовке `RBKmoney-Signature` в формате Base64.

schemes:
  - https
consumes:
  - application/json; charset=utf-8
produces:
  - application/json; charset=utf-8
parameters:
  signature:
    name: RBKmoney-Signature
    in: header
    description: >
      Подпись сообщения, созданная приватным ключом RSA с алгоритмом хеширования
      SHA-256
    required: true
    type: string
tags:
  - name: Event Notifications
    x-displayName: Оповещения
    description: Доставка оповещений о событиях платформы.
